Menstruation-Cycle-App/App_Blog/urls.py
from django.urls import path
from . import views

app_name='App_Blog'


urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/',views.liked,name='liked_post'),
    path('unliked/<pk>/',views.unliked,name='unliked_post'),
    path('my-blog/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit-blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
]


Menstruation-Cycle-App/Home/urls.py
from django.urls import path
from Home import views
app_name='Home'

urlpatterns = [
  
  path('', views.index, name='home'),
  path('contact', views.contact, name ="contact"),
  path('faq', views.faq, name ="faq"),
  path('pcod', views.pcod, name ="pcod"),
  path('selfcare', views.selfcare, name ="selfcare"),
  path('periodtracker', views.periodtracker, name ="periodtracker"),
  path('pcodpredict', views.pcodpredict, name ="pcodpredict"), 
  path('generate_completion', views.generate_completion, name='generate_completion'),
  path('calendar', views.CalendarView.as_view(), name='calendar'),
  path('^event/new/$', views.event, name='event_new'),
  path('^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

 

Menstruation-Cycle-App/StainStrong/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('Home.urls')),
    path('',views.index, name='index'),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



Menstruation-Cycle-App/Home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class UserPeriod(models.Model):
    uid = models.ForeignKey(User,related_name='user_id',on_delete=models.CASCADE)
    lasperioddate = models.DateField('%Y-%m-%d')
    duration = models.IntegerField()

class Event(models.Model):
    description = models.CharField(max_length=500)
    start_time = models.DateTimeField()
    userid = models.ForeignKey(User,related_name="user_identity",on_delete=models.CASCADE)
    mood = models.CharField(max_length=100)
    moodscore = models.IntegerField()

    @property
    def get_html_url(self):
        url = reverse('Home:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

Menstruation-Cycle-App/Home/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from Home.models import Event

class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.CharField(max_length=150)
    message = forms.CharField(widget= forms.Textarea, max_length=2000)

class PeriodTracker(forms.Form):
    lastperiod = forms.DateField(label=" Your last period date ")
    duration = forms.IntegerField(label=" Duration of your last period ")

class PCODForm(forms.Form):
    follicle_R = forms.FloatField(label=" Follicle No.(R) ")
    follicle_L = forms.FloatField(label=" Follicle No.(L) ")
    skindarkening = forms.FloatField(label=" Skin Darkening(1/0) ")
    hair = forms.FloatField(label=" Hair growth(1/0) ")
    weight = forms.FloatField(label=" Weight gain(1/0) ")
    cycle = forms.FloatField(label=" Cycle(Regular-1/Irregular-0) ")

class EventForm(ModelForm):
  class Meta:
    model = Event
    #fields = '__all__'
    fields =('description','start_time')

Menstruation-Cycle-App/Home/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView
from .forms import ContactForm, PeriodTracker, PCODForm, EventForm
from .models import UserPeriod, Event
from django.http import HttpResponse, HttpRequest
from django.core.mail import message, send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth import get_user_model
import numpy as np
import pandas as pd
import json
from datetime import datetime
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression  
from sklearn.datasets import load_iris  
from sklearn.model_selection import train_test_split
import pickle
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.decorators import login_required
import openai
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.utils.safestring import mark_safe
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime, timedelta, date
import calendar
from .utils import Calendar
from django.contrib.auth.mixins import LoginRequiredMixin


Pkl_Filename = "Home/Pickle_RL_Model.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    Pickled_LR_Model = pickle.load(file)
Pkl_Filename1 = "Home/model_MNB_actual.pkl"
Pkl_Filename2 = "Home/model_NB.pkl" 
with open(Pkl_Filename1, 'rb') as file:  
    Pickled_LR_Model1 = pickle.load(file)
with open(Pkl_Filename2, 'rb') as file:  
    Pickled_LR_Model2 = pickle.load(file)

loaded_vectorizer = pickle.load(open('Home/vectorizer.pickle', 'rb'))


class CalendarView(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = 'Home/calendar.html'

    def get_context_data(self, **kwargs):
        current_user = self.request.user
        dategraph=[]
        scoregraph=[]
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month, current_user.id)
        html_cal = cal.formatmonth(withyear=True)
        queryset = Event.objects.all()
        queryset = queryset.filter(userid_id=current_user)
        if queryset:
            df = pd.DataFrame(list(queryset.values()))
            df.drop(columns = ['userid_id','id','description','mood'],inplace=True)
            print(df)
            dategraph = df['start_time'].tolist()
            scoregraph = df['moodscore'].tolist()
            for i in range(0,len(dategraph)):
                dategraph[i] = str(dategraph[i].date())
                dategraph[i]=dategraph[i].replace("-","")
            print(dategraph)
            print(scoregraph)
            for i in range(len(scoregraph)):
                scoregraph[i] = scoregraph[i]+5
        context['dategraph'] = json.dumps(dategraph)
        context['scoregraph'] = scoregraph
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

@login_required
def event(request, event_id=None):
    current_user = request.user.pk
    queryset = Event.objects.all()
    queryset = queryset.filter(userid_id=current_user)
    #instance = Event()
    if event_id:
        instance = get_object_or_404(queryset, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
            desc = form.cleaned_data['description']
            st = form.cleaned_data['start_time']
            moodlist = moodtracker(request,desc)
            score = moodlist[0]
            mood = moodlist[1]
            p = Event(userid_id=current_user,description=desc,start_time=st,mood=mood,moodscore=score)
            p.save()
            return HttpResponseRedirect(reverse('Home:calendar'))
    return render(request, 'home/event.html', {'form': form})

@login_required
def moodtracker(request,desc):
    text = [desc]
    d = {"sadness": -2 ,"anger": 0 ,"love": 2,"joy":3 ,"fear": -1,"surprise": 1}
    test_result1 = Pickled_LR_Model1.predict(loaded_vectorizer.transform(text))
    test_result2 = Pickled_LR_Model2.predict(loaded_vectorizer.transform(text))
    score = int((test_result1+test_result2)/2)
    mood = (list(d.keys())[list(d.values()).index(int((test_result1+test_result2)/2))])
    return [score,mood]
    

def generate_completion(request):
    openai.api_key = "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"

    prompt = request.POST.get("user_input")
    print(prompt)
    model ="text-davinci-002"
    response="Oh my god just work!!"

    completions = openai.Completion.create(
        engine=model,
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.5,
    )

    response = completions.choices[0].text
    print("Hello")
    print(response)
    return render(request, 'Home/chatbot.html', {'prompt':prompt,'res':response})

def index(request):
    return render(request,'Home/home.html')
def faq(request):
    return render(request,'Home/faq.html')
def pcod(request):
    return render(request,'Home/pcod.html')
def selfcare(request):
    return render(request,'Home/selfcare.html')

class home(ListView):
    template_name='Home/home.html'

@login_required
def periodtracker(request):
    current_user = request.user.pk
    print(current_user)
    lp = "Hi"
    ped = 2
    print("Hello")
    form = PeriodTracker()
    if request.method == 'POST':
        print("Enter")
        form = PeriodTracker(request.POST)
        print("Hello")
        if form.is_valid():
            print("Enter1")
            lp = form.cleaned_data['lastperiod']
            ped = form.cleaned_data['duration']
            print(lp)
            print(ped)
            print(type(current_user))
            p = UserPeriod(uid_id=current_user,lasperioddate=lp,duration=ped)
            p.save()
    queryset = UserPeriod.objects.all()
    queryset = queryset.filter(uid_id=current_user)
    print(queryset)
    if queryset is not None:
        period_start_dates = []
        period_lengths = []
        df = pd.DataFrame(list(queryset.values()))
        df.drop(columns = ['uid_id','id'],inplace=True)
        print(df)
        period_start_dates = df['lasperioddate'].tolist()
        period_lengths = df['duration'].tolist()
        period_gaps=[28]
        period_model = LinearRegression()
        #print(period_start_dates)
        #print(type(period_start_dates))
        temp = str(period_start_dates[-1])
        for i in range(0,len(period_start_dates)):
          period_start_dates[i] = str(period_start_dates[i])
          #print(period_start_dates[i])
          period_start_dates[i]=period_start_dates[i].replace("-","")
          #print(period_start_dates[i])
          period_start_dates[i]=period_start_dates[i][:4]+period_start_dates[i][6:8]+period_start_dates[i][4:6]
          #print(period_start_dates[i])
          if i!=0:
            d=abs(int(period_start_dates[i][6:8])-int(period_start_dates[i-1][6:8]))
            if (int(period_start_dates[i][4:6])!=1):
                  m=abs(int(period_start_dates[i][4:6])-int(period_start_dates[i-1][4:6]))
                  y=int(period_start_dates[i][:4])-int(period_start_dates[i-1][:4])
            else:
                 m=abs(13-int(period_start_dates[i-1][4:6]))
                 y=int(period_start_dates[i][:4])-int(period_start_dates[i-1][:4])-1
            period_gaps.append(int(((30*m)-d)))
        #print(period_start_dates)
        #print(period_gaps)
       
        period_model.fit(np.array(period_start_dates).reshape(-1, 1), period_gaps)
        last_start_date = period_start_dates[-1]
        prediction = period_model.predict(np.array([last_start_date]).reshape(-1, 1))
        print("prediction ",prediction)
        date=float(last_start_date) + prediction[0]
        date= str(date)[:4]+str(date)[4:6]+str(date)[6:8]
        mth=['01','02','03','04','05','06','07','08','09','10','11','12']
        d=date[6:8]
        m=date[4:6]
        y=date[:4]
        no_of_days={'01':'31','02':'28','03':'31','04':'30','05':'31','06':'30','07':'31','08':'31','09':'30','10':'31','11':'30','12':'31'};
        if int(date[6:8])>int(no_of_days[date[4:6]]):
            d=int(date[6:8])-int(no_of_days[date[4:6]])
            if d<10:
                    d='0'+str(d)
            if(date[4:6]!='12'):
                print(date[4:6])
                m=mth[int(date[4:6])]
            else:
                m='01'
                y=int(date[:4])+1
        date=str(y)+'-'+str(d)+'-'+str(m)
        temp = datetime.strptime(temp,'%Y-%d-%m').date()
        date = datetime.strptime(date,'%Y-%d-%m').date()
        middate = temp + (date-temp)/2
    return render(request, 'Home/periodtracker.html', context={'form':form,'date':date,'prevperiod':temp,'middate':middate})

def pcodpredict(request):
    l = []
    inp = []
    res = "Waiting for result"
    y_pred=-1
    form = PCODForm()

Menstruation-Cycle-App/templates/Home/calendar.html
{% extends 'Base.html' %}
{% load google_translate %}
{% load crispy_forms_tags %}
{% block title %} Contact Us {% endblock title %}
{% block body_block %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.js" integrity="sha512-Lii3WMtgA0C0qmmkdCpsG0Gjr6M0ajRyQRQSbTF6BsrVh/nhZdHpVZ76iMIPvQwz1eoXC3DmAg9K51qT5/dEVg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>

{% if scoregraph %}
<div class="row">
  <div class="col-lg-6 col-sm-6" style="margin:0 auto;"> 
    {% google_translate %} 
    <centre><canvas id="myChart2" width="5" height="5" ></canvas></centre> 
</div>
<div class="col-lg-6 col-sm-6" style="margin:0 auto;">  
  {{ calendar }}
</div>
</div>
{% endif %}

<div class="clearfix">
  <br>
<a class="btn btn-info left" href="{% url 'Home:calendar' %}?{{ prev_month }}"> Previous Month </a>
<a class="btn btn-info right" href="{% url 'Home:calendar' %}?{{ next_month }}"> Next Month </a>
<a class="btn btn-info right" href="{% url 'Home:event_new' %}"> New Event </a>
</div>

<!-- {{ calendar }} -->

<script>
    const plugin = {
    id: 'custom_canvas_background_color',
    beforeDraw: (chart) => {
      const ctx = chart.canvas.getContext('2d');
      ctx.save();
      ctx.globalCompositeOperation = 'destination-over';
      ctx.fillStyle = 'lightPink';
      ctx.fillRect(0, 0, chart.width, chart.height);
      ctx.restore();
    }};
    let canvaselement=document.getElementById("myChart2").getContext('2d');
    let l1 = {{dategraph|safe}};
    let d1 = {{ scoregraph }};
    console.log(typeof(d1))
    console.log("Hello")
    console.log(d1)
    let x = [];
    let y = [];
    for (let i in l1) {
  x.push(l1[i]);
}
    console.log(x)
    console.log(typeof(x))
    let l = ['20221001','20221103','20221204','20221205','20230101'];
    console.log(typeof(l))
    console.log(l)
    let d = [-1,1,0,2,-2];
    console.log(typeof(d))
        var config ={
            type: "bar",
            data: {
                labels : x,
                datasets: [{ data: d1,
                backgroundColor: [
                        'rgba(0, 0, 0, 0.9)',
                        'rgba(255, 206, 86, 0.9)',
                        'rgba(173,255,47, 0.9)',
                        'rgba(255,0,0, 0.9)',
                        'rgba(0,0,255, 0.9)',
                        'rgba(128,0,0, 0.9)',
                        'rgba(128,0,128, 0.9)',
                        'rgba(0,128,128, 0.9)',
                        'rgba(255,165,0, 0.9)',
                    ],
            }]
            },
            plugins: [plugin],
            options: {
              scales:{
                x:{
                    type:'time',
                    time: {
                      unit: 'day'
                    }
                },
                },
                plugins: {
                  legend: {
            display: false
         },
         tooltips: {
            enabled: false
         },
                    title: {
                        display: true,
                        text: "Graph"
                    },
        
                },
               
            }
          };
          var myChart2=new Chart(canvaselement,config);
    
  </script>

<style>
    .calendar, .body {
  width: 70%;
  margin: auto;
  font-size: 13px;
  background: #ff748ac4;
         color: #fff;
         font-family: 'Lato', Arial, sans-serif;
}

.calendar tr, .calendar td {
  border: 1px solid black;
}

.calendar th {
  text-align: center;
  font-size: 18px;
  border: 2px solid #fff;
  border-collapse: collapse;
  padding: 15px;
}

.calendar td {
  width: 300px;
  height: 75px;
  padding: 20px 0px 0px 5px;
  border: 2px solid #fff;
  border-collapse: collapse;
}

.month {
  font-size: 25px;
}

.date {
  font-size: 16px;
}

ul {
  height: 100%;
  padding: 0px 5px 0px 20px;
}

a {
  color: #17a2b8;
}

.left {
  float: left;
}

.right {
  float: right;
}

.btn {
  outline: none;
  color: black;
  background-color: transparent;
  box-shadow: 0 0 0 0;
}

.clearfix {
  margin: 15px;
}

























@import url(https://fonts.googleapis.com/css?family=Lato:300,400,700);

     h1 {
         font-family: "proxima-nova",sans-serif;
         letter-spacing: -0.01em;
         font-weight: 700;
         font-style: normal;
         font-size: 60px;
         margin-left: -3px;
         line-height: 1em;
         color: #fff;
         text-align: center;
         margin-bottom: 8px;
         text-rendering: optimizeLegibility;
     }

    .calendar table {
         width: 80%;
         margin: auto;
         border: 1px solid #fff;
         border-collapse: collapse;
     }

</style>

{% endblock %}

Menstruation-Cycle-App/templates/Home/chatbot.html
{% extends 'Base.html' %}
{% load google_translate %}
{% load crispy_forms_tags %}
{% block title %} Contact Us {% endblock title %}
{% block body_block %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>
    .title {
        background-color: #ff748ac4;
        color: #021119;
        text-align: center;
        padding: 100px;
        -webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;
        
        
    }
    
    .letsSpeak {
        background-color: #021119;
        color: white;
        padding-top: 50px;
        padding-bottom: 50px;
        padding-left: 100px;
        padding-right: 100px;
    }
    
    .knowledge {
        background-color: #ff718773;
        color: white;
        padding-top: 50px;
        padding-bottom: 50px;
        padding-left: 100px;
        padding-right: 100px;
    }
    
    .teach {
        background-color: #16a8c7;
        color: white;
        padding-top: 50px;
        padding-bottom: 50px;
        padding-left: 100px;
        padding-right: 100px;
    }
    
    a {
        color: black;
        
    }
    button {
        background-color: #c2454c;
    }
</style>

</head>

<body>

    <div class="title" id="title">
        {% google_translate %}
        <h2>Hi, I'm a chat bot.<br/> Say hi below</h2>
        <a id="icon" href="#letsSpeak"><i class="fa fa-angle-double-down" style="font-size:48px"></i></a>
        </div>

<div class="knowledge">
    <h2>Chat with me!</h2>
    <form action="/home/generate_completion" method="post">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Enter your question " id="userInput" name="user_input">
    <br/>
    <button type="submit" class="w3-button w3-pink" value="Reset Form">Chat</button>
    <br/>
    </form>
    
    {% if prompt %}
    {% if res %}
    <div class="response">{{ res }}</div>
    {% endif %}
    {% endif %}
</div>



{% endblock %}

Menstruation-Cycle-App/templates/Home/contact.html
{% extends 'Base.html' %}
{% load google_translate %}
{% load crispy_forms_tags %}
{% block title %} Contact Us {% endblock title %}
{% block body_block %}

<div class="contactmains">
	<div class="contact">
		{% google_translate %}
		<h1>Contact Me</h1>
		
			<form method="post">
				{{ form | crispy }} 
				{% csrf_token %}
				
				<button type="submit"  class="custom-btn btn-2">Contact Us</button>
	
			</form>
		
	</div>

</div>

{% endblock %}

Menstruation-Cycle-App/templates/Home/home.html
{% extends 'Base.html' %}
{% load google_translate %}
{% load custom_filters %}
{% load static %}
{% block title %} Home {% endblock title %}

{% block body_block %}


<div class="landing-page">
    <br>
    <br>
    {% google_translate %} 
    <div class="upperlanding">

        <h1> <span>Catamenia</span></h>
           

    </div>

    <div class="lowerlanding">
        <img src="{% static 'Home/images/womens-history-month.jpg' %}" alt="">
    </div>

</div>
<div class="Aboutus">
    <h1>About Us</h1>
    <div class="aboutusmain">


        <div class="aboutusimg">

            <img src="{% static 'Home/images/blooddropre.png' %}" alt="">

        </div>
        <div class="aboutuscontent">

            <p style = "text-align:center">Hey strong women! <br> Menstruated is a platform where we all unite to share our first-period stories, feelings, emotions through blogs. You can track your periods and know when your next predicted period is. You should know that you are not alone in the fight against pcods, get tested regularly and know if you are prone to it. You can know the myths/facts, self-care during periods, and much much more! You can also journal your thoughts and feelings and view the mood tracker.<br> Empowered women Empower women. You go, girls!</p>

        </div>
        <div class="aboutusimg">

            <img src="{% static 'Home/images/blooddropre.png' %}" alt="">

        </div>
    </div>
</div>
<div class="reminder">
    <div class="imgrem">
        <img src="{% static 'Home/images/menstrual-calendar.jpg' %}" alt="">

    </div>
    <div class="contentrem">
        <h2>Track Your dates</h2>
        <p>Know your cycle, know yourself! Don't forget your date, Know when you might get your next period. </p>
        <a href="{% url 'Home:periodtracker' %}"><button class="custom-btn btn-2">Predict</button></a>

    </div>

</div>
<div class="Blogmore">
    <h1>Explore Blogs</h1>
    <div class="blogmain">
        <div class="blogimg">
            <img src="{% static 'Home/images/18.png' %}" alt="">

        </div>
        <div class="blogcontent">

            <p>Blogs are the ways to communicate and share your thoughts. Explore how others dealt with their periods, getting stain stories, myths about periods and much more, share your experience too.</p>
            <a href="{% url 'App_Blog:blog_list' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>
        <div class="blogimg">
            <img src="{% static 'Home/images/18.png' %}" alt="">

        </div>
    </div>

</div>
<div class="ever">
    <h1>Let's talk about it</h1>
<div class="everything">

   
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">FAQ's</h2>
            <p>Questions about periods, PMS and more stuff that might be a doubt to you.

            </p>
            <a href="{% url 'Home:faq' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>

    </div>
   
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">PCOD/PCOS</h2>
            <p>Pcos (Polycystic Ovary Syndrome), is common among women nowadays, let's look at it in more detail.
                
                
            </p>
            <a href="{% url 'Home:pcod' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>

    </div>
   
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">Self Care</h2>
            <p>“Taking care of our personal self is not a luxury but an essential need just as food and water!”
                
            </p>
            <a href="{% url 'Home:selfcare' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>

    </div>
</div>

</div>

<div class="Talkabout">
    <h1>Let's Chat</h1>
    <div class="mainchat">
        <div class="rightchat">
            <img src="{% static 'Home/images/35.png' %}" alt="">
            
    
        </div>

        <div class="leftchat">
           
            <p>
             Ask our Chat bot any questions you may have. Feed your curiosity and gain new knowledge.
            </p>
            <a href="{% url 'Home:generate_completion' %}"><button class="custom-btn btn-2">Lets Chat</button></a>
    
        </div>
        <div class="rightchat">
            <img src="{% static 'Home/images/35.png' %}" alt="">
            
    
        </div>
       

    </div>
    
    
   

</div>
<div class="poll">
    <h1>PCOD Prediction</h1>
    <div class="pollmain">
        <div class="pollimg">
            <img src="{% static 'Home/images/34.png' %}" alt="">
        </div>
        <div class="pollcontent">
            <p> PCOD is faced by many women around the world. Feed in your test results to know if you are prone to PCOD</p>
            <a href="{% url 'Home:pcodpredict' %}"><button class="custom-btn btn-2">Test yourself</button></a>
        </div>

    </div>

</div>

<div class="contacthome">
    <h1>Mood Tracker</h1>
    <div class="contactmain">
        <div class="contactcon">
            <p>Use our calendar as your digital journal and tell us how you feel. You can also graphically see your mood changes</p>

            <a href="{% url 'Home:calendar' %}"><button class="custom-btn btn-2">Open my diary</button></a>

        </div>
       <div class="contactimg">
            <img src="{% static 'Home/images/1292419.png' %}" alt="">
        </div>
    </div>
</div>


<div class="contacthome">
    <h1>Contact Us</h1>
    <div class="contactmain">
        <div class="contactcon">
            <p>Contact us if you find anything you want to share, it could be questions, issues or enhancements regarding this website.</p>

            <a href="{% url 'Home:contact' %}"><button class="custom-btn btn-2">Contact us</button></a>

        </div>
       <div class="contactimg">
            <img src="{% static 'Home/images/contact.png' %}" alt="">
        </div>
    </div>
</div>

<footer class="footermain">
    <div class="footerhead">
        <h1> <span>C</span>atamenia</h>
    </div>
    <div class="footermaini">
        <div class="footerimg">
            <img src="{%  static 'Home/images/24.png' %}" alt="">
        </div>
    
    
        <div class="footercontent">
            <p>Team: TroubleShooters</p>
            <p>SheBuilds</p>
           
    
        </div>
    
        <div class="footerimg">
            <img src="{%  static 'Home/images/24.png' %}" alt="">
        </div>    

    </div>
        
   

  
</footer>


{% endblock %}

Menstruation-Cycle-App/templates/Home/pcodpredict.html
{% extends 'Base.html' %}
{% load google_translate %}
{% load crispy_forms_tags %}
{% block title %} Contact Us {% endblock title %}
{% block body_block %}

<div class="contactmains">
	<div class="contact">
		{% google_translate %}
		<h1>PCOD Predictor</h1>
		
			<form method="post">
				{{ form | crispy }} 
				{% csrf_token %}
				
				<button type="submit"  class="custom-btn btn-2">Predict</button>
                <h1>{{ res }}</h1>
			</form>
		
	</div>

</div>

{% endblock %}