Menstruation-Cycle-App/App_Login/urls.py
from django.urls import path
from  . import views

app_name= 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up,name='signup'),
    path('signin/', views.login_page,name='signin'),
    path('logout/', views.logout_user,name='logout'),
    path('profile/', views.profile,name='profile'),
    path('change_profile/', views.user_change,name='user_change'),
    path('password/', views.pass_change,name='pass_change'),
    path('change-profile-image/', views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic,name='change_pro_pic'),
       
]

Menstruation-Cycle-App/Home/urls.py
from django.urls import path
from Home import views
app_name='Home'

urlpatterns = [
  
  path('', views.index, name='home'),
  path('contact', views.contact, name ="contact"),
  path('faq', views.faq, name ="faq"),
  path('pcod', views.pcod, name ="pcod"),
  path('selfcare', views.selfcare, name ="selfcare"),
  path('periodtracker', views.periodtracker, name ="periodtracker"),
  path('pcodpredict', views.pcodpredict, name ="pcodpredict"), 
  path('generate_completion', views.generate_completion, name='generate_completion'),
  path('calendar', views.CalendarView.as_view(), name='calendar'),
  path('^event/new/$', views.event, name='event_new'),
  path('^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

 

Menstruation-Cycle-App/StainStrong/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('Home.urls')),
    path('',views.index, name='index'),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



Menstruation-Cycle-App/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')


Menstruation-Cycle-App/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django.forms import fields
from App_Login.models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label=" Email Address ",required=True)
    lastperioddate = forms.DateField(label=" Your last period date ")
    periodduration = forms.IntegerField(label = "Period duration ")
    class Meta:
        model= User
        fields =('username','email','password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model=User
        fields=('username', 'email','first_name','last_name','password')
        
class ProfilePic(forms.ModelForm):
    class Meta:
        model= UserProfile
        fields=['profile_pic',]

Menstruation-Cycle-App/App_Login/views.py
from App_Login.forms import ProfilePic, SignUpForm, UserProfileChange
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm,UserProfileChange,ProfilePic
from django.contrib.auth import get_user_model
from Home.models import UserPeriod
from .models import User


# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered =False
    if request.method =='POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered=True
            lp = form.cleaned_data['lastperioddate']
            pd = form.cleaned_data['periodduration']
            un = form.cleaned_data['username']
            queryset = User.objects.all()
            id = queryset.filter(username=un).values('id')
            id = id.first()['id']
            p = UserPeriod(uid_id=id,lasperioddate=lp,duration=pd)
            p.save()
    dict = {'form':form,'registered':registered}

    return render(request,'App_Login/signup.html',context=dict)



def login_page(request):
    form= AuthenticationForm()
    if request.method =='POST':
        form =AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

    return render(request, 'App_Login/login.html', context={'form':form})



@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))




@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})


@login_required   
def user_change(request):
    current_user = request.user
   
    form = UserProfileChange(instance=current_user)
    if request.method =='POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)  
    return render(request, 'App_Login/change_profile.html', context={'form':form})



@login_required   
def pass_change(request):
    current_user= request.user
    changed = False
    form = PasswordChangeForm(current_user)

    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True

    return render(request,'App_Login/pass_change.html',context={'form':form,'changed':changed})




@login_required   
def add_pro_pic(request):
    form = ProfilePic()
    if request.method =='POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit = False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html',context={'form':form})


@login_required  
def change_pro_pic(request):
    form =ProfilePic(instance= request.user.user_profile)
    if request.method=='POST':
        form = ProfilePic(request.POST, request.FILES, instance = request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html',context={'form':form})







Menstruation-Cycle-App/templates/App_Login/change_profile.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Change User Profile {% endblock title %}


{% block body_block %}
<div class="userchangeprofile">
    <div class="userchangeprofilebox">
        <h2>User Profile Change</h2>
<form  method="post">
    {{form|crispy}}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Change</button>

</form>

    </div>

</div>

{% endblock body_block %}

Menstruation-Cycle-App/templates/App_Login/login.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock title %}


{% block body_block %}
<div class="mainbasecontainer">
    <div class="form">
        <h2>Login Your Account</h2>
    <form  method="post">
        {{form|crispy}}
    
        {% csrf_token %}
        <button type="submit" class="custom-btn btn-2">Login</button>
    
    </form>
    </div>
    
</div>

{% endblock body_block %}

Menstruation-Cycle-App/templates/App_Login/pass_change.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Password Change Page {% endblock title %}


{% block body_block %}

{% if changed %}

<div class="alert alert-success">

    Password Change Successfully

</div>

{% endif %}



<h2>Password Change</h2>
<form  method="post">
    {{form|crispy}}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Change</button>

</form>
{% endblock body_block %}

Menstruation-Cycle-App/templates/App_Login/pro_pic_add.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profile Pic Update {% endblock title %}


{% block body_block %}
<div class="addprofilepic">
    <h2>Add Your Profile Picture</h2>
    <div class="addprofilepicbox">
        <form  method="post" enctype="multipart/form-data">
            {{form|crispy}}
        
            {% csrf_token %}
            <button type="submit" class="custom-btn btn-2">Add Picture</button>
        
        </form>

    </div>


</div>


{% endblock body_block %}

Menstruation-Cycle-App/templates/App_Login/profile.html
{% extends 'Base.html' %}
{% load static %}
{% block title %} Profile Page {% endblock title %}


{% block body_block %}

    
<div class="profile-container">
<h2> Your Profile</h2>


<div class="profile-card">

{% if user.user_profile %}

<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="120px"  alt="">
<br>
<a href="{% url 'App_Login:change_pro_pic'%} " class="btn btn-info btn-sm">Change Profile</a>

{% else %}
<img src="/media/download.jpg" class="rounded-circle"  width="120px" alt="">
<br>
<a href="{% url 'App_Login:add_pro_pic'%}" class="btn btn-info btn-sm">Change Profile Pic</a>

{% endif %}
<p>Username :{{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name :{{ user.first_name }} {{ user.last_name }}</p>

<br>
<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm"> Change Profile Info</a>
{% endblock body_block %}
</div>
</div>

Menstruation-Cycle-App/templates/App_Login/signup.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create New Account{% endblock title %}


{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account created successfully <a href="{%  url 'App_Login:signin' %}"> Login Here</a>
</div>
{% else %}
<div class="enter">
<h1>Create New Account</h1>
<form method="post">
    
   {{ form | crispy }} 
   {% csrf_token %}
   <button type="submit" style="width: 12rem;" class="custom-btn btn-2">Create Account</button>

</form>
<br>
<p>Already Have an account? <a href="{% url 'App_Login:signin' %}"><button type="submit" class="custom-btn btn-2">Login Here</button></a></p>
{% endif %}
</div>
{% endblock %}