Menstruation-Cycle-App/App_Blog/urls.py
from django.urls import path
from . import views

app_name='App_Blog'


urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/',views.liked,name='liked_post'),
    path('unliked/<pk>/',views.unliked,name='unliked_post'),
    path('my-blog/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit-blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
]


Menstruation-Cycle-App/App_Login/urls.py
from django.urls import path
from  . import views

app_name= 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up,name='signup'),
    path('signin/', views.login_page,name='signin'),
    path('logout/', views.logout_user,name='logout'),
    path('profile/', views.profile,name='profile'),
    path('change_profile/', views.user_change,name='user_change'),
    path('password/', views.pass_change,name='pass_change'),
    path('change-profile-image/', views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic,name='change_pro_pic'),
       
]

Menstruation-Cycle-App/Home/urls.py
from django.urls import path
from Home import views
app_name='Home'

urlpatterns = [
  
  path('', views.index, name='home'),
  path('contact', views.contact, name ="contact"),
  path('faq', views.faq, name ="faq"),
  path('pcod', views.pcod, name ="pcod"),
  path('selfcare', views.selfcare, name ="selfcare"),
  path('periodtracker', views.periodtracker, name ="periodtracker"),
  path('pcodpredict', views.pcodpredict, name ="pcodpredict"), 
  path('generate_completion', views.generate_completion, name='generate_completion'),
  path('calendar', views.CalendarView.as_view(), name='calendar'),
  path('^event/new/$', views.event, name='event_new'),
  path('^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

 

Menstruation-Cycle-App/StainStrong/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('Home.urls')),
    path('',views.index, name='index'),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



Menstruation-Cycle-App/templates/Base.html
<!DOCTYPE html>
{% load static %}
{% load google_translate %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <title>

        {% block title %}

        Menstruated

        {% endblock %}

    </title>

    <link href="{% static 'css/base.css' %}" rel="stylesheet" />

</head>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<body>
    <!-- <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <img style="width: 24px;
                margin-left: 5px;
                margin-top: 5px;
            " src="https://www.pngkey.com/png/full/72-724918_vector-drip-clip-art-blood-drop-clipart-png.png" alt="">
            </li>
            <li class="nav-item active" id="mainname" style="align-items: center;
            margin: 0rem 8px;
            font-size: 26px;
            color: white;
            font-weight: bold;
            margin-right: 1rem;">Menstruated</li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>


            {% if user.is_authenticated %}


            <!-- <li class="nav-item active">
                <img src="/media/images (1).png" alt="">
            </li> -->





    <!-- <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Blog:blog_list' %}">Blogs</a>
            <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
            </li>
            </li>
        
            <li>
                <a class="nav-link" style="margin-left: 9rem;" href=""> {{ user.username }}</a>
               
            {% else %}

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
            </li>
            {% endif %}

        </ul>

    </nav> -->
    <section class="nav-bar">
        <div class="nav-container">
            <div class="logo" style=" color: white;
            font-weight: 700;
            font-size: 1.5rem;
            text-decoration: none;
            ">

                <a href="" style="display: flex;
                  
                align-items: center;
                   
                color: white;
                 text-decoration: none;"><img style="width: 20px;margin-right: 1rem;" src="{%  static 'Home/images/logo.png' %}"alt="">Catamenia </a>
            </div>
            <nav>
                <div class="nav-mobile"><a id="nav-toggle" href="#!"><span></span></a></div>
                <ul class="nav-list">
                    <li>
                        <a href="{% url 'index' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    
                    <li>
                        <a href="#">Blogs</a>
                        <ul class="nav-dropdown">
                            <li>
                                <a href="{% url 'App_Blog:blog_list' %}">Blogs</a>
                            </li>
                            <li>
                                <a href="{% url 'App_Blog:create_blog' %}">Publish Blog</a>
                            </li>
                            <li>
                                <a href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'Home:generate_completion' %}">Let's Chat</a>
                    </li>
                    
                    <li>
                        <a href="{% url 'App_Login:profile' %}">{{ user.username }}</a>
                    </li>

                    <li>
                        <a href="{% url 'App_Login:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'App_Login:signup' %}">Sign Up</a>
                    </li>
                    <li>
                        <a href="{% url 'App_Login:signin' %}">Login</a>
                    </li>

                    {% endif %}

                </ul>

            </nav>
        </div>
    </section>

    <div class="containermain">
        <div class="main">

            {% block body_block %}
            

            {% endblock %}

        </div>
    </div>

</body>
<script>
    (function ($) {
        $(function () {
            $('nav ul li a:not(:only-child)').click(function (e) {
                $(this).siblings('.nav-dropdown').toggle();
                $('.dropdown').not($(this).siblings()).hide();
                e.stopPropagation();
            });
            $('html').click(function () {
                $('.nav-dropdown').hide();
            });
            $('#nav-toggle').click(function () {
                $('nav ul').slideToggle();
            });
            $('#nav-toggle').on('click', function () {
                this.classList.toggle('active');
            });
        });
    })(jQuery);

</script>

</html>